version: '3.4'

services:
  swnr:
    image: swnr
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 30000:30000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
